### ISSUE TITLE
Compatibility with LimeSurvey 4.5 ?

### ISSUE THREAD

**Issue by dregad** [SondagesPro/LS-AuthWPbyDB#1]
Hello,

I tried to install the plugin following the [documentation](https://extensions.sondages.pro/admin-authentification/limesurvey-authentification-by-wordpress/documentation.html), but I do not see it in the Plugin manager.

I also tried to install by uploading the ZIP file from the Plugin manager via the _Upload & Install_ button, but in this case an error message pops up :
```
Configuration file config.xml does not exist.
```

I am running LimeSurvey Version 4.5.0+210412.  Is the plugin compatible with this version ? Or maybe I am doing something wrong ?

Thanks in advance for your help.

**Comment by Shnoulle** [comment]
It's not tested, I think it can work.

You can create a config.xml file and test if it's OK and make a pull request please ?

**Comment by dregad** [comment]
Thanks for responding so quickly !

Pardon my ignorance, but I am just an occasional user of LimeSurvey and don't know much about its internals. I do not really understand what you are asking me to do - Where should I put this file and what should its contents be ?

**Comment by Shnoulle** [comment]
Sample of config.xml : https://github.com/SondagesPro/LS-ResetSubmitted/blob/main/config.xml

I don't work on 4/5.X compatibility currently (and don't use this plugin since years now).

**Comment by dregad** [comment]
OK I did some research and based on [this page](https://manual.limesurvey.org/Make_your_plugin_compatible_with_LS4) I tried to create a new zip file with a config.xml file as follows:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<config>
    <metadata>
        <name>AuthLDAP</name>
        <type>plugin</type>
        <creationDate>2014-04-01</creationDate>
        <lastUpdate>2021-06-21</lastUpdate>
        <author>Denis Chenu</author>
        <authorUrl>https://sondages.pro</authorUrl>
        <supportUrl>https://github.com/SondagesPro/LS-AuthWPbyDB/issues</supportUrl>
        <version>1.2.0</version>
        <license>GNU General Public License version 3 or later</license>
        <description><![CDATA[Authentification via WordPress Plugin for LimeSurvey]]></description>
    </metadata>

    <compatibility>
        <version>4.0</version>
    </compatibility>

    <updaters disabled="disabled">
    </updaters>
</config>
```

With this the plugin seems to install successfully,
```
The plugin was successfully updated. You might need to deactivate it and activate it again to apply changes.
```
however it does not appear in the list of plugins, and I don't know how to reach the configuration page

**Comment by Shnoulle** [comment]
Pull request … did fix ` <name>AuthWPbyDB</name>`

**Comment by dregad** [comment]
> did fix ` <name>AuthWPbyDB</name>`

Merci le copy/paste :flushed: 

I'll send a PR after testing
