### ISSUE TITLE
Layout problem on login page when AuthWPbyDB is default method

### ISSUE THREAD

**Issue by dregad** [SondagesPro/LS-AuthWPbyDB#2]
When the setting _Check to make default authentication method_ is checked, the Username / password fields on the LimeSurvey 
login page do not have the right layout:

- Checked 
  ![image](https://user-images.githubusercontent.com/449891/122780768-6f19be80-d2af-11eb-9cc4-7ca8a171a758.png)
- Not checked
  ![image](https://user-images.githubusercontent.com/449891/122780495-2eba4080-d2af-11eb-982b-1145fc839640.png)

**Comment by Shnoulle** [comment]
Ok,

Easy fix, the HTML between 3.X and 2.X unsure when.

it work else ?

**Comment by dregad** [comment]
Apart from that, everything seems to work perfectly so far. I will post another issue if I find something else.

**Comment by Shnoulle** [comment]
Can you make the pull request for the config file ? 
I update the HTML when it's done.

**Comment by Shnoulle** [comment]
https://github.com/SondagesPro/LS-AuthWPbyDB/commit/e0efdfcaf3743986f39fe83d8d3025df38c58dc5

**Comment by dregad** [comment]
Thanks for the fix, I confirm it looks good now with version 1.2.1
